/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'muhamed' at '10/14/17 2:12 PM' with Gradle 2.10
 *
 * @author muhamed, @date 10/14/17 2:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
